# Generated by Django 4.1.3 on 2022-11-12 04:26

from django.db import migrations, models
import django.db.models.deletion
import versionfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scdn', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name': 'library', 'verbose_name_plural': 'libraries'},
        ),
        migrations.AlterModelOptions(
            name='permissions',
            options={'verbose_name': 'permission', 'verbose_name_plural': 'permissions'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': 'resource', 'verbose_name_plural': 'resources'},
        ),
        migrations.AddField(
            model_name='library',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scdn.library'),
        ),
        migrations.AddField(
            model_name='library',
            name='version',
            field=versionfield.fields.VersionField(default='0.0.1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='scdn.library'),
        ),
    ]
